spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: false
  sql:
    init:
      encoding: UTF-8
      continue-on-error: true
      mode: always

server:
  port: 80

---

spring:
  config:
    activate:
      on-profile: localDB
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mariadb://localhost:3306/lofDev?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 1234

---

spring:
  config:
    activate:
      on-profile: devServerDB
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${lof.mariadb.url.dev}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ${lof.mariadb.password}

---

spring:
  config:
    activate:
      on-profile: mainServerDB
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${lof.mariadb.url.main}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ${lof.mariadb.password}